CREATE TABLE USERS(
EMPLOYEE_ID INTEGER NOT NULL,
JOBTYPE VARCHAR(20) NOT NULL,
USERNAME VARCHAR(20)NOT NULL,
PSSWORD VARCHAR(20) NOT NULL,
FNAME VARCHAR(15) NOT NULL,
LNAME VARCHAR(15) NULL,
ADDRESS VARCHAR(25) NOT NULL,
EMAIL VARCHAR(30) NOT NULL,
PNUM NUMBER (10) NOT NULL

);

CREATE TABLE REIMBURSEMENTS(
EMPLOYEE_ID INTEGER NOT NULL,
JOBTYPE VARCHAR(20) NOT NULL,
AVAIL_AMOUNT NUMBER(4,2), 
PEND_AMOUNT NUMBER(4,2)
);

INSERT INTO USERS VALUES(1,'EMPLOYEE','JOHN5969', 'JOHNNY1024', 'JOHN','LEGEND','AMERICAN HERO 123, HOUSTON, TX, 77053', 'JOHN.LEGEND@COMPANY.COM',8885689620);