DROP TABLE USERS;
DROP TABLE REIMBURSEMENTS;
DROP TABLE TRANSACTIONS;

CREATE TABLE USERS(
EMPLOYEE_ID NUMBER NOT NULL,
JOBTYPE VARCHAR2(80) NOT NULL,
JOBPOS VARCHAR2(80) NOT NULL,
REPORTSTO VARCHAR2(20) NOT NULL,
USERNAME VARCHAR2(80)NOT NULL, 
PSSWORD VARCHAR2(80) NOT NULL,
FNAME VARCHAR2(30) NOT NULL,
LNAME VARCHAR2(30) NOT NULL,
ADDRESS VARCHAR2(80) NOT NULL,
EMAIL VARCHAR(80) NOT NULL,
PNUM VARCHAR2(20) NOT NULL
);

CREATE TABLE REIMBURSEMENTS(
EMPLOYEE_ID NUMBER NOT NULL,
JOBTYPE VARCHAR2(80) NOT NULL,
STATUS NUMBER(38) NOT NULL,
UC_AMT NUMBER(10,2)NOT NULL,
SEM_AMT NUMBER(10,2) NOT NULL,
CERT_PREP_AMT NUMBER(10,2) NOT NULL,
CERT_AMT NUMBER(10,2) NOT NULL,
TECH_WRIT_AMT NUMBER(10,2) NOT NULL,
OTR_AMT NUMBER(10,2) NOT NULL,
STATUS_TIME TIMESTAMP (9),
NEXT_REIMB_AVAl TIMESTAMP(5),
AVAIL_AMT NUMBER(10,2) NOT NULL,
PEND_AMT NUMBER(10,2) NOT NULL,
REIMB_AMT NUMBER(10,2) NOT NULL,
REIMB_RESET TIMESTAMP(5) NOT NULL
);

CREATE TABLE TRANSACTIONS(
EMPLOYEE_ID NUMBER NOT NULL,
TRANS_ID NUMBER NOT NULL,
AMOUNT_REIMB NUMBER (10,2),
REIMB_PEND NUMBER (10,2),
REIMB_RESET TIMESTAMP(5)
);

--USERS
INSERT INTO USERS (EMPLOYEE_ID,JOBTYPE,JOBPOS,REPORTSTO,USERNAME,PSSWORD,FNAME,LNAME,ADDRESS,EMAIL,PNUM) VALUES (37253000,'BENCO','SALES','--','MJTHEGREAT1990','THRILLER50','MICHAEL','JACKSON','55468 MOONWALK DR, HOUSTON, TX', 'MICHAEL.JACKSON@COGNIZANT.COM',5565469632);
INSERT INTO USERS (EMPLOYEE_ID,JOBTYPE,JOBPOS,REPORTSTO,USERNAME,PSSWORD,FNAME,LNAME,ADDRESS,EMAIL,PNUM) VALUES (27253000,'DS','SALES','--','MJTHEGREAT1990','THRILLER50','MICHAEL','JACKSON','55468 MOONWALK DR, HOUSTON, TX', 'MICHAEL.JACKSON@COGNIZANT.COM',5565469632);
INSERT INTO USERS (EMPLOYEE_ID,JOBTYPE,JOBPOS,REPORTSTO,USERNAME,PSSWORD,FNAME,LNAME,ADDRESS,EMAIL,PNUM) VALUES (17253000,'DH','SALES','--','MJTHEGREAT1990','THRILLER50','MICHAEL','JACKSON','55468 MOONWALK DR, HOUSTON, TX', 'MICHAEL.JACKSON@COGNIZANT.COM',5565469632);
INSERT INTO USERS (EMPLOYEE_ID,JOBTYPE,JOBPOS,REPORTSTO,USERNAME,PSSWORD,FNAME,LNAME,ADDRESS,EMAIL,PNUM) VALUES (07253000,'EMPLOYEE','SALES','--','MJTHEGREAT1990','THRILLER50','MICHAEL','JACKSON','55468 MOONWALK DR, HOUSTON, TX', 'MICHAEL.JACKSON@COGNIZANT.COM',5565469632);


--REIMBURSEMENTS

--TRANSACTIONS







--
--CREATE SEQUENCE ID_CREATE
--START WITH 0000
--INCREMENT BY 1
--;

