DROP TABLE USERS;
DROP TABLE REIMBURSEMENTS;
DROP TABLE TRANSACTIONS;
DROP SEQUENCE ID_CREATE; 
DROP SEQUENCE TRANS_ID_CREATE;
DROP TRIGGER START_TRANS_REC;
--CREATE DATABASE

CREATE TABLE USERS(
EMPLOYEE_ID NUMBER NOT NULL,
JOBTYPE NUMBER(35) NOT NULL,
REPORTSTO NUMBER(35) NOT NULL,
USERNAME VARCHAR2(80)NOT NULL, 
PSSWORD VARCHAR2(80) NOT NULL,
FNAME VARCHAR2(30) NOT NULL,
LNAME VARCHAR2(30) NOT NULL,
ADDRESS VARCHAR2(80) NOT NULL,
EMAIL VARCHAR(80) NOT NULL,
PNUM VARCHAR2(20) NOT NULL
);

CREATE TABLE REIMBURSEMENTS(
EMPLOYEE_ID NUMBER NOT NULL,
JOBTYPE NUMBER(35) NOT NULL,
REASON VARCHAR2(60) NOT NULL,
DATE_COMP DATE NOT NULL,
START_TIME DATE,
END_TIME DATE,
STATUS NUMBER(38) NOT NULL,
STATUS_TIME TIMESTAMP,
AVAIL_AMT NUMBER(10,2) NOT NULL,
PEND_AMT NUMBER(10,2) NOT NULL,
REIMB_AMT NUMBER(10,2) NOT NULL,
REIMB_RESET NUMBER(25) NOT NULL
);

CREATE TABLE TRANSACTIONS(
EMPLOYEE_ID NUMBER NOT NULL,
TRANS_ID NUMBER NOT NULL,
AVAIL_AMT NUMBER(10,2) NOT NULL,
REIMB_AMT NUMBER (10,2),
PEND_AMT NUMBER (10,2),
REIMB_RESET NUMBER(5)
);
--SEQUENCES
CREATE SEQUENCE ID_CREATE 
START WITH 07253000
INCREMENT BY 1
;

CREATE SEQUENCE TRANS_ID_CREATE
START WITH 00001
INCREMENT BY 1
;

--TRIGGERS
/
--STARTS A TRANSACTION LOG ONCEE USER SUBMITS REIMB FORM
CREATE OR REPLACE TRIGGER START_TRANS_REC
AFTER INSERT ON REIMBURSEMENTS
FOR EACH ROW 
BEGIN
INSERT INTO TRANSACTIONS
(EMPLOYEE_ID,TRANS_ID,AVAIL_AMT,REIMB_AMT,PEND_AMT,REIMB_RESET)
VALUES
(:NEW.EMPLOYEE_ID,TRANS_ID_CREATE.NEXTVAL,:NEW.AVAIL_AMT,:NEW.REIMB_AMT,:NEW.PEND_AMT,:NEW.REIMB_RESET);
END;
/

--USERS
INSERT INTO USERS (EMPLOYEE_ID,JOBTYPE,REPORTSTO,USERNAME,PSSWORD,FNAME,LNAME,ADDRESS,EMAIL,PNUM) VALUES (37253000,4,5,'MJTHEGREAT1990','THRILLER50','MICHAEL','JACKSON','55468 MOONWALK DR, HOUSTON, TX', 'MICHAEL.JACKSON@RUNTIME.COM',5565469632);
INSERT INTO USERS (EMPLOYEE_ID,JOBTYPE,REPORTSTO,USERNAME,PSSWORD,FNAME,LNAME,ADDRESS,EMAIL,PNUM) VALUES (27253000,3,4,'IAMTHEGOAT','6RINGZ','MICHAEL','JORDAN ','123456 NBA LEGEND LANE, CHICAGO, IL', 'MICHAEL.JORDAN@RUNTIME.COM',5565469632);
INSERT INTO USERS (EMPLOYEE_ID,JOBTYPE,REPORTSTO,USERNAME,PSSWORD,FNAME,LNAME,ADDRESS,EMAIL,PNUM) VALUES (17253000,2,3,'MIKE','THRILLER50','MIKE','JAMES','55468 TYLER DR, HOUSTON, TX', 'MICHAEL.JACKSON@RUNTIME.COM',5565469632);
INSERT INTO USERS (EMPLOYEE_ID,JOBTYPE,REPORTSTO,USERNAME,PSSWORD,FNAME,LNAME,ADDRESS,EMAIL,PNUM) VALUES (07253000,1,2,'JONES','THRILLER50','JONES','DREW','55468 FRANK DR, HOUSTON, TX', 'MICHAEL.JACKSON@RUNTIME.COM',5565469632);
INSERT INTO USERS (EMPLOYEE_ID,JOBTYPE,REPORTSTO,USERNAME,PSSWORD,FNAME,LNAME,ADDRESS,EMAIL,PNUM) VALUES (07253001,1,2,'TOMMY','THRILLER50','THOMAS','FORD','55468 BOB DR, HOUSTON, TX', 'MICHAEL.JACKSON@RUNTIME.COM',5565469632);
INSERT INTO USERS (EMPLOYEE_ID,JOBTYPE,REPORTSTO,USERNAME,PSSWORD,FNAME,LNAME,ADDRESS,EMAIL,PNUM) VALUES (07253002,1,2,'HERALD','THRILLER50','HERALD','TELLER','55468 MILK DR, HOUSTON, TX', 'MICHAEL.JACKSON@RUNTIME.COM',5565469632);
INSERT INTO USERS (EMPLOYEE_ID,JOBTYPE,REPORTSTO,USERNAME,PSSWORD,FNAME,LNAME,ADDRESS,EMAIL,PNUM) VALUES (07253003,1,2,'BLAH','THRILLER50','BLAINE','JOHNSON','55468 YETER DR, HOUSTON, TX', 'MICHAEL.JACKSON@RUNTIME.COM',5565469632);
INSERT INTO USERS (EMPLOYEE_ID,JOBTYPE,REPORTSTO,USERNAME,PSSWORD,FNAME,LNAME,ADDRESS,EMAIL,PNUM) VALUES (07253004,1,2,'YEAH','THRILLER50','YASMINE','MICHAEL','55468 THYSER DR, HOUSTON, TX', 'MICHAEL.JACKSON@RUNTIME.COM',5565469632);



--REIMBURSEMENTS
INSERT INTO REIMBURSEMENTS (EMPLOYEE_ID, JOBTYPE,REASON,DATE_COMP,START_TIME, END_TIME, STATUS,STATUS_TIME,AVAIL_AMT,PEND_AMT,REIMB_AMT,REIMB_RESET) VALUES (07253004,1,'hi', CURRENT_TIMESTAMP,'01-JAN-2001','01-JAN-2001',2,CURRENT_TIMESTAMP,1000.00,500.00,0.00,365);







--TRANSACTIONS
--AUTO GENERATED










--ALL REIMBURSEMENTS SUBMITTED 
SELECT * FROM REIMBURSEMENTS  WHERE STATUS = 1;

--ALL REIMBURSEMENTS APPROVED  BY DS
SELECT * FROM REIMBURSEMENTS  WHERE STATUS = 2;

--ALL REIMBURSEMENTS APPROVED  BY DH
SELECT * FROM REIMBURSEMENTS  WHERE STATUS = 3;

--ALL REIMBURSEMENTS APPROVED  BY BENCO
SELECT * FROM REIMBURSEMENTS  WHERE STATUS = 4;

--ALL REIMBURSEMENTS  APPROVED AND  SENT OUT 
SELECT * FROM REIMBURSEMENTS  WHERE STATUS = 2;